### ISSUE TITLE
[1.12.2] Crash when looking up in JEI

### ISSUE THREAD

**Issue by MasterEnderman** [TehNut-Mods/ResourcefulCrops#54] opened 2017-11-03 03:17 UTC
Just try to look up the mod in JEI and the game crashes.

ResourcefulCrops: 2.1.0-61
Forge: 14.23.0.2528
Jei: 4.8.0.111
Crash-Report: https://pastebin.com/uPkT9Mq1

**Comment by TehNut** [comment] 2017-11-03 03:30
Dupe of #51 

Fixed in ae3ead60900c982cbfd5ec44ae9d56ac6dfd4146. I guess I never ran a build.

**Closed as completed by TehNut** 2017-11-03 03:30 UTC
