### ISSUE TITLE
Crash with WAILA

### ISSUE THREAD

**Issue by MCEventHorizon** [TehNut-Mods/ResourcefulCrops#35] opened 2016-07-25 20:23 UTC
http://pastebin.com/ExuaGp87

**Comment by TehNut** [comment] 2016-07-25 22:01
What crop? What's the JSON for it? I need some information.

**Comment by MCEventHorizon** [comment] 2016-07-26 10:06
All Crops.

**Comment by MCEventHorizon** [comment] 2016-07-26 10:06
Every time you look at a Crop it crashes.

**Comment by Teibidh** [comment] 2016-09-13 05:19
Can confirm this is happening for 1.8.9 with WAILA 1.1.4.171 and RC 1.3.0-48. In my particular case though it only appears to happen with custom seeds. With no WAILA, just RC, my custom seeds work fine. As soon as I look at a plant resulting from a custom seed with WAILA installed though (just BC and WAILA) it goes poof.  Doesn't seem to matter what material, color code or name of custom seed is, monkeyed with all of these making sure I didn't use silly characters.

**Comment by TehNut** [comment] 2016-09-13 05:30
I'm sorry, but unless you can reproduce this in 1.9 or 1.10, I'm not going to look into it. 1.8 was a very short lived MC version and is not supported.

**Comment by Teibidh** [comment] 2016-09-13 05:44
Fair enough, but the pastebin from the original issue opener reflects the exact same error and it appears as though that user is using 1.10.2 ... Assuming you get this worked out it would be great if you'd backport the fix to the 1.8.9 version.

And as requested, in case it helps (not sure if JSON changed since 1.8.9), here are two that I tried to use:
"32": {
    "name": "Juice",
    "tier": 2,
    "amount": 4,
    "input": "enderio:bucketXpjuice",
    "output": {
      "name": "enderio:bucketXpjuice",
      "amount": 8,
      "meta": 0
    },
    "color": "#b2a2bf"
},
"33": {
    "name": "Gaianite",
    "tier": 2,
    "amount": 4,
    "input": "resourcesfulcrops:itemMaterial:0",
    "output": {
      "name": "resourcefulcrops:itemMaterial:0",
      "amount": 8,
      "meta": 0
    },
    "color": "#b2a2bf"
  },

**Comment by TehNut** [comment] 2017-03-03 05:45
Should be fixed in 2.0 releases.

**Closed as completed by TehNut** 2017-03-03 05:45 UTC
